name: fission-web-api
version: '1.6.0'
category: API
author: Brooklyn Zelenka
maintainer: hello@brooklynzelenka.com
copyright: © 2019 Brooklyn Zelenka
license: AGPL-3.0-or-later
license-file: LICENSE
github: fission-suite/web-api
tested-with: GHC==8.6.4
extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  # Warn about too little
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  # Warn about too much
  - -Wredundant-constraints
  # Prettier Development
  - -fhide-source-paths

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - OverloadedLabels
  - OverloadedLists
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeSynonymInstances
  - TemplateHaskell
  - TypeOperators
  - ViewPatterns

dependencies:
  - aeson
  - aeson-casing
  - base
  - cryptonite
  - bytestring
  - data-default-class
  - data-has
  - ekg-wai
  - envy
  - http-client
  - http-client-tls
  - http-media
  - http-types
  - lens
  - mime-types
  - monad-logger
  - random-bytestring
  - resource-pool
  - rio
  - rio-orphans
  - scientific
  - selda
  - selda-sqlite
  - servant
  - servant-auth-server
  - servant-auth-swagger
  - servant-client
  - servant-exceptions
  - servant-multipart
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - streaming-commons
  - streamly
  - swagger2
  - text
  - time
  - unliftio
  - uuid
  - uuid-types
  - wai
  - wai-cors
  - wai-extra
  - wai-logger
  - warp
  - warp-tls
  - word8

library:
  source-dirs: src

executables:
  fission-web:
    main: Main.hs
    source-dirs: app
    dependencies:
      - fission-web-api
      - wai-logger
    ghc-options:
      - -threaded
      - -rtsopts
      - -flate-specialise
      - -with-rtsopts=-N
      - -with-rtsopts=-T
      - -O2

tests:
  fission-doctest:
    main: Main.hs
    source-dirs: test/doctest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - directory
      - directory-tree
      - doctest
      - Glob
      - lens-aeson
      - QuickCheck
      - yaml

  fission-test:
    main: Main.hs
    source-dirs:
      - src
      - test
      - test/testsuite
    ghc-options:
      - -fhpc
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - hspec
      - hspec-wai
      - hspec-wai-json
      - fission-web-api
      - tasty
      - tasty-hunit
      - tasty-hspec
      - tasty-smallcheck
      - tasty-rerun
      - transformers

  # fission-coverage-code:
  #   main: Main.hs
  #   source-dirs: test/code-coverage
  #   ghc-options:
  #     - -fhpc
  #   dependencies:
  #     - base
  #     - fission-web-api
  #     - process
  #     - regex-compat

  # fission-coverage-docs:
  #   main: Main.hs
  #   source-dirs: test/doc-coverage
  #   dependencies:
  #     - doctest
  #     - fission-web-api
  #     - process
  #     - regex-compat

  fission-lint:
    main: Main.hs
    source-dirs: test/lint
    dependencies:
      - base
      - hlint
      - rio

benchmarks:
  fission-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - criterion
      - fission-web-api
