name: ipfs-api
version: '0.0.1.0'
category: API
author: Brooklyn Zelenka
maintainer: hello@brooklynzelenka.com
copyright: © 2019 Brooklyn Zelenka
license: Apache-2.0
license-file: LICENSE
github: fission-suite/ipfs-api
tested-with: GHC==8.6.5
extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  # Warn about too little
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  # Warn about too much
  - -Wredundant-constraints
  # Prettier Development
  - -fhide-source-paths
  # - -fprint-unicode-syntax

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - OverloadedLabels
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeSynonymInstances
  - TemplateHaskell
  - TypeOperators

dependencies:
  - aeson
  - aeson-casing
  - base
  - cryptonite
  - bytestring
  - data-default-class
  - data-has
  - ekg-wai
  - envy
  - etc
  - http-client
  - http-client-tls
  - http-media
  - lens
  - monad-logger
  - random-bytestring
  - resource-pool
  - rio
  - rio-orphans
  - scientific
  - selda
  - selda-sqlite
  - servant
  - servant-auth-server
  - servant-client
  - servant-server
  - servant-multipart
  - streaming-commons
  - text
  - time
  - typed-process
  - unliftio
  - uuid
  - uuid-types
  - wai
  - wai-extra
  - wai-logger
  - warp
  - word8

library:
  source-dirs: src

executables:
  server:
    main: Main.hs
    source-dirs: app
    dependencies:
      - ipfs-api
      - wai-logger
    ghc-options:
      - -threaded
      - -rtsopts
      - -flate-specialise
      - -with-rtsopts=-N
      - -with-rtsopts=-T
      - -O2

tests:
  fission-doctest:
    main: Main.hs
    source-dirs: test/doctest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - doctest
      - Glob
      - QuickCheck
      - ipfs-api

  fission-test:
    main: Main.hs
    source-dirs:
      - src
      - test
      - test/testsuite
    ghc-options:
      - -fhpc
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - hspec
      - hspec-wai
      - hspec-wai-json
      - ipfs-api
      - tasty
      - tasty-hunit
      - tasty-hspec
      - tasty-smallcheck
      - tasty-rerun
      - transformers

  fission-docs:
    main: Main.hs
    source-dirs: test/docs
    dependencies:
      - doctest
      - ipfs-api
      - process
      - regex-compat

  fission-coverage:
    main: Main.hs
    source-dirs: test/coverage
    ghc-options:
      - -fhpc
    dependencies:
      - base
      - ipfs-api
      - process
      - regex-compat

  fission-lint:
    main: Main.hs
    source-dirs: test/lint
    dependencies:
      - base
      - hlint
      - rio

benchmarks:
  fission-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - criterion
      - ipfs-api
