resolver: lts-19.0
allow-newer: true # Needed for servant-ekg

packages:
  - fission-cli
  - fission-core
  - fission-web-api
  - fission-web-client
  - fission-web-server
  - hs-ucan
  - ipfs

extra-deps:
  - amazonka-1.6.1
  - amazonka-core-1.6.1
  - amazonka-route53-1.6.1
  - constraints-deriving-1.1.1.2
  - dimensions-2.1.1.0
  - ekg-core-0.1.1.7
  - ekg-statsd-0.2.5.0
  - hfsevents-0.1.6
  - lzma-clib-5.2.2
  - raven-haskell-0.1.4.0
  - servant-ekg-0.3.1
  - unliftio-core-0.1.2.0
  - powerdns-0.2.2

ghc-options:
  "$everything": -haddock

nix:
  enable: true
  pure: true
  shell-file: shell.nix
