resolver: lts-17.4

allow-newer: true

packages:
  - fission-cli
  - fission-core
  - fission-web-api
  - fission-web-client
  - fission-web-server

extra-deps:
  - alex-3.2.6
  - amazonka-1.6.1
  - constraints-deriving-1.1.1.1
  - cryptostore-0.2.1.0
  - dimensions-2.1.0.0
  - happy-1.20.0
  - hfsevents-0.1.6
  - ipfs-1.3.0.0
  - lzma-clib-5.2.2
  - raven-haskell-0.1.4.0
  - rescue-0.4.0
  - servant-auth-0.4.0.0
  - servant-auth-server-0.4.6.0
  - servant-auth-swagger-0.2.10.1
  - servant-swagger-ui-redoc-0.3.3.1.22.3
  - servant-websockets-2.0.0
  - text-time-0.3.1
  - unliftio-core-0.1.2.0

  # For ipfs-1.3.0.0
  - bytebuild-0.3.7.0
  - byteslice-0.2.5.2
  - bytesmith-0.3.7.0
  - contiguous-0.5.1
  - ip-1.7.3
  - natural-arithmetic-0.1.2.0
  - primitive-offset-0.2.0.0
  - run-st-0.1.1.0
  - tuples-0.1.0.0

nix:
  enable:     false
  pure:       true
  shell-file: shell.nix
