version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - fission-ipfs-api-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Run tests
          command: stack test
      - run:
          name: Install executable
          command: stack install
      - save_cache:
          name: Cache Dependencies
          key: fission-ipfs-api-{{ checksum "package.yaml" }}
          paths:
            - "~/.stack-work"
            - "~/.stack"
      - store_artifacts: # upload build artifact for display in CircleCI
          path: ~/.local/bin/fission-ipfs-api-server
          destination: fission-ipfs-api-server
