name: 🧰 Cachix
on:
  pull_request:
  push:
    branches: [main]
jobs:
  cachix:
    name: 🖥️  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: 📤 Checkout
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

      - uses: cachix/install-nix-action@v19
        name: ❄️  Set up Nix
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: |
            substituters = https://cache.iog.io
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - uses: cachix/cachix-action@v12
        name: 🧰 Cachix
        with:
          name: fission-codes
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: 🏗️  Build
        run: nix build -L '.#fission-cli' '.#fission-server'
