name: "Cachix"
on:
  pull_request:
  push:
    branches: [main]
jobs:
  cachix:
    name: ${{ matrix.os }} / Cachix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.3.4
      name: 📤 Checkout
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: cachix/install-nix-action@v13
      name: ❄️  Set up Nix
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v9
      name: 🧰 Cachix
      with:
        name: fission-2
        extraPullNames: https://hydra.iohk.io
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: 🏗️  Build
      run: nix-build -A fission-cli.components.exes.fission | cachix push fission-2
