name: ❄️ Nix Build

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  stack:
    name: 🖥️  ${{ matrix.os }} ❄️  Nix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 📤 Checkout
      - uses: DeterminateSystems/nix-installer-action@main
        name: ❄️ Set up Nix
      - uses: cachix/cachix-action@v12
        name: 🧰 Cachix
        with:
          name: fission-codes
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: 👷 Build
        run: |
          nix build .#fission-cli --accept-flake-config
          nix build .#fission-server --accept-flake-config
