name: Continuous Integration

on:
  push:         { "branches": [ "master" ] }
  pull_request: { "branches": [ "master" ] }

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: 📥 Checkout repository
      uses: actions/checkout@v1

    - name: 🔑 Dependency Cache Key
      id: dep_cache_key
      run: echo ::set-output name=key::$(md5sum stack.yaml.lock | awk '{print $1}{print "4"}')

    - name: 💾 Cache Dependencies
      id: cache_deps
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ steps.dep_cache_key.outputs.key }}

    - name: 🔑 Artifact Cache Key
      id: art_cache_key
      run: echo ::set-output name=key::$(git branch)

    - name: 💾 Cache Artifacts
      id: cache_arts
      uses: actions/cache@v1
      with:
        path: ./.stack-work/dist
        key: ${{ matrix.os }}-${{ steps.art_cache_key.outputs.key }}

    - name: Test
      run: |
        stack test --no-terminal
